# Generated by Django 4.2.15 on 2024-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=25)),
                ("title_one", models.CharField(max_length=60, null=True)),
                ("title_two", models.CharField(blank=True, max_length=60, null=True)),
                ("title_three", models.CharField(blank=True, max_length=60, null=True)),
                ("title_four", models.CharField(blank=True, max_length=60, null=True)),
                ("x_url", models.URLField()),
                ("f_url", models.URLField()),
                ("ig_url", models.URLField()),
                ("linkedin_url", models.URLField()),
            ],
        ),
    ]
