# Generated by Django 4.2.15 on 2025-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend_dataskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=150)),
                ('percentage', models.CharField(blank=True, max_length=15)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frontendskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=150)),
                ('percentage', models.CharField(blank=True, max_length=15)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=25)),
                ('resume_link', models.URLField(default='https://drive.google.com/drive/folders/1csFCVIVj7sSqbnHXLAR2K75Md36XYbeB')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, default='mail@mail.com', max_length=254)),
                ('address', models.CharField(blank=True, default='location', max_length=100)),
                ('title_one', models.CharField(max_length=60, null=True)),
                ('title_two', models.CharField(blank=True, max_length=60, null=True)),
                ('title_three', models.CharField(blank=True, max_length=60, null=True)),
                ('title_four', models.CharField(blank=True, max_length=60, null=True)),
                ('x_url', models.URLField()),
                ('f_url', models.URLField()),
                ('ig_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField(default='https//:github.com')),
                ('about_title', models.CharField(blank=True, default='text', max_length=200)),
                ('birthday', models.CharField(blank=True, default='text', max_length=20)),
                ('degree', models.CharField(blank=True, default='text', max_length=150)),
                ('job_type', models.CharField(blank=True, default='text', max_length=150)),
                ('location', models.CharField(blank=True, default='text', max_length=150)),
                ('bio', models.TextField(default='text')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=300)),
                ('p_description', models.TextField()),
                ('p_image', models.ImageField(upload_to='portfolio/')),
                ('live_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service-images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
