# Generated by Django 4.2.15 on 2025-06-13 22:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='brief_bio',
            field=ckeditor.fields.RichTextField(default='text'),
        ),
    ]
