# Generated by Django 4.2.15 on 2024-08-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
