# Generated by Django 4.2.15 on 2024-08-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_generalinfo_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField()),
            ],
        ),
    ]
