# Generated by Django 4.2.15 on 2024-08-27 12:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
