# Generated by Django 4.2.15 on 2024-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_alter_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="address",
            field=models.CharField(blank=True, default="location", max_length=100),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="email",
            field=models.EmailField(
                blank=True, default="mail@mail.com", max_length=254
            ),
        ),
    ]
