# Generated by Django 4.2.15 on 2024-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_generalinfo_address_generalinfo_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="about_title",
            field=models.CharField(blank=True, default="text", max_length=200),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="bio",
            field=models.TextField(default="text"),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="birthday",
            field=models.CharField(blank=True, default="text", max_length=20),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="degree",
            field=models.CharField(blank=True, default="text", max_length=150),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="job_type",
            field=models.CharField(blank=True, default="text", max_length=150),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="location",
            field=models.CharField(blank=True, default="text", max_length=150),
        ),
    ]
