# Generated by Django 4.2.15 on 2024-10-09 14:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_generalinfo_about_title_generalinfo_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinfo",
            name="bio",
            field=ckeditor.fields.RichTextField(default="text"),
        ),
    ]
