# Generated by Django 4.2.15 on 2024-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0008_skillset"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillset",
            name="skill",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
