# Generated by Django 4.2.15 on 2024-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0009_skillset_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skillset2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(blank=True, max_length=150)),
                ("percentage", models.CharField(blank=True, max_length=15)),
                ("value", models.IntegerField()),
            ],
        ),
    ]
