# Generated by Django 4.2.15 on 2024-10-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0010_skillset2"),
    ]

    operations = [
        migrations.RenameModel(old_name="Skillset", new_name="Backend_dataskill",),
        migrations.RenameModel(old_name="Skillset2", new_name="Frontendskill",),
    ]
