# Generated by Django 4.2.15 on 2024-10-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0011_rename_skillset_backend_dataskill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="github_url",
            field=models.URLField(default="https//:github.com"),
        ),
    ]
