# Generated by Django 4.2.15 on 2024-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0012_generalinfo_github_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("subject", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("sent_time", models.DateTimeField(blank=True, null=True)),
                ("is_success", models.BooleanField(default=False)),
                ("is_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
