# Generated by Django 4.2.15 on 2025-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_service_body_service_image_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='resume_link',
            field=models.URLField(default='https://drive.google.com/drive/folders/1csFCVIVj7sSqbnHXLAR2K75Md36XYbeB'),
        ),
    ]
