# Generated by Django 4.2.15 on 2025-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_generalinfo_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='ig_url',
            field=models.URLField(blank=True),
        ),
    ]
