# Generated by Django 4.2.15 on 2025-05-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_generalinfo_ig_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=300)),
                ('p_description', models.TextField()),
                ('p_image', models.ImageField(upload_to='portfolio/')),
                ('live_link', models.URLField(blank=True)),
            ],
        ),
    ]
