"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment configuration 
ENVIRONMENT = config('ENVIRONMENT', default="development")
ENVIRONMENT = "production"

SECRET_KEY = config('SECRET_KEY')

# DEBUG = True
# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'development':
    DEBUG = True
else:
    DEBUG = True

# ALLOWED_HOSTS = []

# Hosting platforms 
if ENVIRONMENT == "development":
    ALLOWED_HOSTS = []
else:
    # ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'sevenwings.onrender.com']
    ALLOWED_HOSTS = ['*'] # allow any host...
    
# Application definition

# CSRF_TRUSTED_ORIGINS = [
#     'https://sevenwings.onrender.com'
# ]

# INTERNAL_IPS = [
#     "127.0.0.1",
#     'localhost',
# ]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # created app 
    "application",
    "case",
    # "blog",
    "acct",
    
    # text editor
    # 'ckeditor_uploader',
    # "ckeditor", 
    "django_prose_editor",
    'django_summernote'
]

# X_FRAME_OPTIONS = 'SAMEORIGIN'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

# Use WhiteNoise to serve static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"

# # CKEditor settings
# CKEDITOR_UPLOAD_PATH = "uploads/"  # for file uploads (requires ckeditor_uploader)
# CKEDITOR_IMAGE_BACKEND = "pillow"  # for image processing
# CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js' 

# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'Full',
#         'height': 300,
#         'width': '100%',
#     },
# }

# SUMMERNOTE_CONFIG = {
#     'iframe': False,
#     'summernote': {
#         'width': '100%',
#         'height': '300px',
#     },
#     # 'attachment_require_authentication': True,
# }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",

#         # 'ENGINE': 'django.db.backends.postgresql',
#         # 'NAME': 'portfolio_db',
#         # 'USER': 'postgres',
#         # 'PASSWORD': "iarowosola#%4956i",
#         # 'HOST': 'localhost',
#         # 'PORT': '5432'
#     }
# }

AUTH_USER_MODEL = "acct.CustomUser"


if ENVIRONMENT == "development":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        'default':dj_database_url.parse(config("DATABASE_URL"))
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / 'static/'
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Image management 
# media files (Images, videos)
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Mail-set up 
# if ENVIRONMENT == "development":
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# else:

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = "smtp.googlemail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD') # app password...
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')

# using mailersend 
# settings.py

MAILERSEND_API_KEY = "mlsn.ebc2156e7ab06ca509bd9bcf83a651985554eaf51837d01ef3b77ecd448b29e9"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.mailersend.net"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "iarowosola@yahoo.com"
# MAILERSEND_SMTP_USERNAME = "MS_2vh2ZU@test-p7kx4xwwyeeg9yjr.mlsender.net"
EMAIL_HOST_PASSWORD = MAILERSEND_API_KEY
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# EMAIL_BACKEND = 'project.mailersend_backend.MailerSendBackend'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# MAILERSEND_API_KEY = 'YOUR_MAILERSEND_API_KEY'  # Replace with your actual MailerSend API key
# DEFAULT_FROM_EMAIL = 'iarowosola25@gmail.com'

# backports.zoneinfo==0.2.1;python_version<"3.9"


        