# Generated by Django 4.2.15 on 2025-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('live', models.URLField()),
                ('repo', models.URLField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField(default='some-description')),
            ],
        ),
    ]
