# Generated by Django 4.2.15 on 2025-06-14 06:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='body',
            field=ckeditor.fields.RichTextField(default='Service details'),
        ),
    ]
