# Generated by Django 4.2.15 on 2025-06-14 07:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_service_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(upload_to='clients/')),
                ('client_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
